<a href="https://colab.research.google.com/github/PragnyaVijayan/pandas_practice/blob/main/03_Grouping/Regiment/Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Regiment

### Introduction:

Special thanks to: http://chrisalbon.com/ for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [13]:
import pandas as pd

### Step 2. Create the DataFrame with the following values:

In [14]:
raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'],
        'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'],
        'name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze', 'Jacon', 'Ryaner', 'Sone', 'Sloan', 'Piger', 'Riani', 'Ali'],
        'preTestScore': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
        'postTestScore': [25, 94, 57, 62, 70, 25, 94, 57, 62, 70, 62, 70]}

### Step 3. Assign it to a variable called regiment.
#### Don't forget to name each column

In [15]:
raw_data.keys()

dict_keys(['regiment', 'company', 'name', 'preTestScore', 'postTestScore'])

In [16]:
df = pd.DataFrame(raw_data, columns=['regiment', 'company', 'name', 'preTestScore', 'postTestScore'])
df

      regiment company      name  preTestScore  postTestScore
0   Nighthawks     1st    Miller             4             25
1   Nighthawks     1st  Jacobson            24             94
2   Nighthawks     2nd       Ali            31             57
3   Nighthawks     2nd    Milner             2             62
4     Dragoons     1st     Cooze             3             70
5     Dragoons     1st     Jacon             4             25
6     Dragoons     2nd    Ryaner            24             94
7     Dragoons     2nd      Sone            31             57
8       Scouts     1st     Sloan             2             62
9       Scouts     1st     Piger             3             70
10      Scouts     2nd     Riani             2             62
11      Scouts     2nd       Ali             3             70

### Step 4. What is the mean preTestScore from the regiment Nighthawks?

In [17]:
condition = (df['regiment'] == 'Nighthawks')
df.loc[condition][['preTestScore']].mean()

preTestScore    15.25
dtype: float64

### Step 5. Present general statistics by company

In [18]:
df.groupby('company').describe(include='all')

        regiment                                                        ...  \
           count unique         top freq mean  std  min  25%  50%  75%  ...
company                                                                 ...
1st            6      3  Nighthawks    2  NaN  NaN  NaN  NaN  NaN  NaN  ...
2nd            6      3  Nighthawks    2  NaN  NaN  NaN  NaN  NaN  NaN  ...

        postTestScore                                                          \
               unique top freq       mean        std   min    25%   50%   75%
company
1st               NaN NaN  NaN  57.666667  27.485754  25.0  34.25  66.0  70.0
2nd               NaN NaN  NaN  67.000000  14.057027  57.0  58.25  62.0  68.0


          max
company
1st      94.0
2nd      94.0

[2 rows x 44 columns]

### Step 6. What is the mean of each company's preTestScore?

In [19]:
df.groupby('company')['preTestScore'].mean()

company
1st     6.666667
2nd    15.500000
Name: preTestScore, dtype: float64

### Step 7. Present the mean preTestScores grouped by regiment and company

In [20]:
df.groupby(['company', 'regiment'])['preTestScore'].mean()

company  regiment
1st      Dragoons       3.5
         Nighthawks    14.0
         Scouts         2.5
2nd      Dragoons      27.5
         Nighthawks    16.5
         Scouts         2.5
Name: preTestScore, dtype: float64

### Step 8. Present the mean preTestScores grouped by regiment and company without heirarchical indexing

In [22]:
df.groupby(['company', 'regiment'])['preTestScore'].mean().unstack()

regiment  Dragoons  Nighthawks  Scouts
company
1st            3.5        14.0     2.5
2nd           27.5        16.5     2.5

### Step 9. Group the entire dataframe by regiment and company

In [29]:
df.groupby(['regiment', 'company']).mean(numeric_only=True)

                    preTestScore  postTestScore
regiment   company
Dragoons   1st               3.5           47.5
           2nd              27.5           75.5
Nighthawks 1st              14.0           59.5
           2nd              16.5           59.5
Scouts     1st               2.5           66.0
           2nd               2.5           66.0

### Step 10. What is the number of observations in each regiment and company

In [32]:
df.groupby(['company', 'regiment']).size()

company  regiment
1st      Dragoons      2
         Nighthawks    2
         Scouts        2
2nd      Dragoons      2
         Nighthawks    2
         Scouts        2
dtype: int64

### Step 11. Iterate over a group and print the name and the whole data from the regiment

In [37]:
for regiment, company in df.groupby('regiment'):
  print(regiment)
  print(company)

Dragoons
   regiment company    name  preTestScore  postTestScore
4  Dragoons     1st   Cooze             3             70
5  Dragoons     1st   Jacon             4             25
6  Dragoons     2nd  Ryaner            24             94
7  Dragoons     2nd    Sone            31             57
Nighthawks
     regiment company      name  preTestScore  postTestScore
0  Nighthawks     1st    Miller             4             25
1  Nighthawks     1st  Jacobson            24             94
2  Nighthawks     2nd       Ali            31             57
3  Nighthawks     2nd    Milner             2             62
Scouts
   regiment company   name  preTestScore  postTestScore
8    Scouts     1st  Sloan             2             62
9    Scouts     1st  Piger             3             70
10   Scouts     2nd  Riani             2             62
11   Scouts     2nd    Ali             3             70